### ISSUE TITLE
Unable to Ride Striders

### ISSUE THREAD

**Issue by Luthorius** [Qzimyion/BucketEm#7]
With BucketEm installed, players are no longer able to mound Saddled Striders by right clicking on them.

Steps to reproduce:

1. Set up a modded installation and add the latest version of FabricAPI and BucketEm
2. Boot up the game and load into a new world
3. Spawn in a Strider, equip it with a Saddle
4. Right click to try and mount

Expected Results: The player being able to mound the Stider as you can in vanilla.

Actual Results: NOTHING!!!!

This is a problem I'd previously observed months ago on a 1.20.1 modpack I'd put together, but there where too many mod and I hadn't the time to investigate the cause.
Having just set up a fresh modpack for 1.21 I observed the same issue, thought about what mods would have any impact on Strider interactions, removed BucketEm, lo and behold the issue was gone. Then tested it in an isolated environment and the issue persisted with just BucketEm.
Really wholesome mod, I do hope you have time to see to this problem.

**Comment by Qzimyion** [comment]
Found out about the issue, it was simple Mixin Typo :P 

Anyways, the fixed version for both 1.21 and other versions should be out in a few minutes.

**Comment by Qzimyion** [comment]
Also, thanks for reporting the bug.
