### ISSUE TITLE
Frogs cant be bucketed

### ISSUE THREAD

**Issue by Yo-Snowpro** [Qzimyion/BucketEm#9]
Simpily I was going on a trip and I thought a frog would be nice to have when i tried to bucket it I couldnt :/

**Comment by Qzimyion** [comment]
What version is the bug occuring on ?

**Comment by Yo-Snowpro** [comment]
1.21

**Comment by Qzimyion** [comment]
The bug has been fixed in the next version of the mod which will come out shortly.
